name: Portfolio Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Markdown linter
      run: sudo apt-get install -y markdownlint

    - name: Lint Markdown files
      run: markdownlint portfolio.md
